pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
        echo "maven version is fetched successfully "
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
        echo "all the stages are completed successfully"
        echo "this is i have implemented the webhook concept of triggerring the pipeline of jenkins"
      }
      
    }
  }
}
