pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        echo "maven version is fetched successfully"
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
        echo "all the stages are completed successfully"
        echo "this is i have implemented the webhook concept of triggering the pipeline of jenkins"
      }
    }
    stage('Docker Version') {
      agent {
        docker { image 'docker:latest' }
      }
      steps {
        sh 'docker --version'
        echo "docker version fetched successfully"
      }
    }
  }
}
